language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package' && ci/sbt-deploy.sh
  && ci/gh-pages.sh
after_script:
- rm -rf ci
env:
  global:
  - secure: dZU2gSJnI3XNPiewD1WI7n7isDUxdPosL9wUd4iEco6iCYcOkJAKFZZd6QfL+dieYs27xDSEquUdzyCABKrHSIGCx2sBRCgofiErLRgM9haRW5XKWdFIyDBNLkVnARvbzrqJI4E0LfMPzFYFJRXlo+pon5AZoOYONC5hgTAugsA=
  - secure: UJtXfxoHOsDyAU8raKsAP3QQHAbyZVMZVEi/WkBZwnQTSM1HMGf++sSG+nt1uKAdFDxZ2BT/K8cumk38huKVoBZ9wkIlbXsguh8vS+TH3Mz4stlIsHsdYK6IWSVmL6W0Y+PrGGnx8R6NyT9Th11NX+5JE16Mof9PvjUkDTrXL/8=
